// editorReducer
export const SET_CURRENTIMAGE = "SET_CURRENTIMAGE";

// imagesReducer
export const FETCH_IMAGES = "FETCH_IMAGES";
export const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
export const FETCH_IMAGES_FAILURE = "FETCH_IMAGES_FAILURE";
export const UPDATE_IMAGES = "UPDATE_IMAGES";
export const ADD_IMAGE = "ADD_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
export const RESET_IMAGES = "RESET_IMAGES";

// regionsReducer
export const FETCH_REGIONS = "FETCH_REGIONS";
export const FETCH_REGIONS_SUCCESS = "FETCH_REGIONS_SUCCESS";
export const FETCH_REGIONS_FAILURE = "FETCH_REGIONS_FAILURE";
export const RESET_REGIONS = "RESET_REGIONS";
export const GET_EMPTY_REGIONS = "GET_EMPTY_REGIONS";
export const UPDATE_REGIONS = "UPDATE_REGIONS";
